create sequence hibernate_sequence start 1 increment 1;

create table ad (
    id int8 generated by default as identity,
    filename varchar(255),
    tag varchar(255),
    text varchar(2048),
    user_id int8,
    car_id int8,
    primary key (id)
);

create table car (
    id int8 generated by default as identity,
    body_type varchar(255),
    brand varchar(255),
    fuel varchar(255),
    mod varchar(255),
    price float8 not null,
    transmission varchar(255),
    type_of_drive varchar(255),
    volume float8 not null,
    year int4 not null,
    user_id int8,
    primary key (id)
);

create table user_role (
    user_id int8 not null,
    roles varchar(255)
);

create table usr (
    id int8 not null,
    activation_code varchar(255),
    active boolean not null,
    email varchar(255),
    password varchar(255) not null ,
    username varchar(255) not null ,
    primary key (id)
);

alter table if exists ad
    add constraint ad_user_fk
    foreign key (user_id) references usr;

alter table if exists ad
    add constraint ad_car_fk
    foreign key (car_id) references car;

alter table if exists car
    add constraint car_user_fk
    foreign key (user_id) references usr;

alter table if exists user_role
    add constraint user_role_user_fk
    foreign key (user_id) references usr;